import { initializeApp } from "firebase/app";
import { getFirestore, collection, addDoc } from "firebase/firestore";
import { firebaseConfig } from "./src/Firebase/firebase.js";

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const products = [
  // LARGE category
  {
    name: "Oishi Prawn Cracker Spicy 50/60g",
    price: 830,
    stock: 100,
    category: "FAMILY",
    image: "",
  },
  {
    name: "Oishi Prawn Cracker Spicy [by pcs]",
    price: 16.6,
    stock: 100,
    category: "FAMILY",
    image: "",
  },
  {
    name: "Oishi Prawn Cracker Sweet 50/60g",
    price: 830,
    stock: 100,
    category: "FAMILY",
    image: "",
  },
  {
    name: "Oishi Prawn Cracker Sweet [by pcs]",
    price: 16.6,
    stock: 100,
    category: "FAMILY",
    image: "",
  },
  {
    name: "Oishi Prawn Cracker Plain 50/60g",
    price: 830,
    stock: 100,
    category: "FAMILY",
    image: "",
  },
  {
    name: "Oishi Prawn Cracker Plain [by pcs]",
    price: 16.6,
    stock: 100,
    category: "FAMILY",
    image: "",
  },
  {
    name: "Oishi Prawn Cracker Salted Egg 30/60g",
    price: 850,
    stock: 100,
    category: "FAMILY",
    image: "",
  },
  {
    name: "Oishi Prawn Cracker Salted Egg [by pcs]",
    price: 17,
    stock: 100,
    category: "FAMILY",
    image: "",
  },
  {
    name: "Kire Yummy Flakes 50/45g",
    price: 830,
    stock: 100,
    category: "FAMILY",
    image: "",
  },
  {
    name: "Kire Yummy Flakes [by pcs]",
    price: 16.6,
    stock: 100,
    category: "FAMILY",
    image: "",
  },
  {
    name: "Pods Vegetarian Pea Snacks 50/60g",
    price: 830,
    stock: 100,
    category: "FAMILY",
    image: "",
  },
  {
    name: "Pods Vegetarian Pea Snacks [by pcs]",
    price: 16.6,
    stock: 100,
    category: "FAMILY",
    image: "",
  },

  // BEERMATCH category
  {
    name: "Potato Fries Cheese 50/50g",
    price: 755,
    stock: 100,
    category: "BEERMATCH",
    image: "",
  },
  {
    name: "Potato Fries Cheese [by pcs]",
    price: 15.1,
    stock: 100,
    category: "BEERMATCH",
    image: "",
  },
  {
    name: "Potato Fries Plain Salted 50/50g",
    price: 755,
    stock: 100,
    category: "BEERMATCH",
    image: "",
  },
  {
    name: "Potato Fries Plain Salted [by pcs]",
    price: 15.1,
    stock: 100,
    category: "BEERMATCH",
    image: "",
  },
  {
    name: "Potato Fries Barbecue 50/50g",
    price: 755,
    stock: 100,
    category: "BEERMATCH",
    image: "",
  },
  {
    name: "Potato Fries Barbecue [by pcs]",
    price: 15.1,
    stock: 100,
    category: "BEERMATCH",
    image: "",
  },
  {
    name: "Potato Fries Tomato Ketchup 50/50g",
    price: 755,
    stock: 100,
    category: "BEERMATCH",
    image: "",
  },
  {
    name: "Potato Fries Tomato Ketchup [by pcs]",
    price: 15.1,
    stock: 100,
    category: "BEERMATCH",
    image: "",
  },
  {
    name: "Crackling Salt & Vinegar 50/50g",
    price: 755,
    stock: 100,
    category: "BEERMATCH",
    image: "",
  },
  {
    name: "Crackling Salt & Vinegar [by pcs]",
    price: 15.1,
    stock: 100,
    category: "BEERMATCH",
    image: "",
  },
  {
    name: "Kire Yummy Flakes Spicy 50/60",
    price: 755,
    stock: 100,
    category: "BEERMATCH",
    image: "",
  },
  {
    name: "Kire Yummy Flakes Spicy [by pcs]",
    price: 15.1,
    stock: 100,
    category: "BEERMATCH",
    image: "",
  },

  // SUNDAYS category
  {
    name: "Sundays Orange 120/35g",
    price: 2200,
    stock: 100,
    category: "SUNDAYS",
    image: "",
  },
  {
    name: "Sundays Melon 120/35g",
    price: 2200,
    stock: 100,
    category: "SUNDAYS",
    image: "",
  },
  {
    name: "Sundays Mango 120/35g",
    price: 2200,
    stock: 100,
    category: "SUNDAYS",
    image: "",
  },
  {
    name: "Sundays Pineapple 120/35g",
    price: 2200,
    stock: 100,
    category: "SUNDAYS",
    image: "",
  },
  {
    name: "Sundays Orange Mango 120/35g",
    price: 2200,
    stock: 100,
    category: "SUNDAYS",
    image: "",
  },

  // MARSHMALLOW category
  {
    name: "O'Puff Marshmallow Ube 30/84g",
    price: 870,
    stock: 100,
    category: "MARSHMALLOW",
    image: "",
  },
  {
    name: "O'Puff Marshmallow Chocolate 30/84g",
    price: 870,
    stock: 100,
    category: "MARSHMALLOW",
    image: "",
  },
  {
    name: "O'Puff Marshmallow Mango 30/84g",
    price: 870,
    stock: 100,
    category: "MARSHMALLOW",
    image: "",
  },
  {
    name: "O'Puff Marshmallow Matcha Green Tea 30/84g",
    price: 870,
    stock: 100,
    category: "MARSHMALLOW",
    image: "",
  },

  // BREADPAN category
  {
    name: "Breadpan Cheese & Onion",
    price: 680,
    stock: 100,
    category: "BREADPAN",
    image: "",
  },
  {
    name: "Breadpan Cheese & Onion [by pcs]",
    price: 6.8,
    stock: 100,
    category: "BREADPAN",
    image: "",
  },
  {
    name: "Breadpan Garlic Toast",
    price: 680,
    stock: 100,
    category: "BREADPAN",
    image: "",
  },
  {
    name: "Breadpan Garlic Toast [by pcs]",
    price: 6.8,
    stock: 100,
    category: "BREADPAN",
    image: "",
  },
  {
    name: "Breadpan Butter Toast",
    price: 680,
    stock: 100,
    category: "BREADPAN",
    image: "",
  },
  {
    name: "Breadpan Butter Toast [by pcs]",
    price: 6.8,
    stock: 100,
    category: "BREADPAN",
    image: "",
  },
  {
    name: "Breadpan White Cheddar Cheese",
    price: 680,
    stock: 100,
    category: "BREADPAN",
    image: "",
  },
  {
    name: "Breadpan White Cheddar Cheese [by pcs]",
    price: 6.8,
    stock: 100,
    category: "BREADPAN",
    image: "",
  },

  // PINATSU category
  {
    name: "Pinatsu Garlic & Salt 100/32g",
    price: 680,
    stock: 100,
    category: "PINATSU",
    image: "",
  },
  {
    name: "Pinatsu Seaweed 100/32g",
    price: 680,
    stock: 100,
    category: "PINATSU",
    image: "",
  },

  // FROOZE category
  {
    name: "Frooze Pineapple 24/230ml",
    price: 500,
    stock: 100,
    category: "FROOZE",
    image: "",
  },
  {
    name: "Frooze Orange 24/230ml",
    price: 500,
    stock: 100,
    category: "FROOZE",
    image: "",
  },
  {
    name: "Frooze Apple 24/230ml",
    price: 500,
    stock: 100,
    category: "FROOZE",
    image: "",
  },

  // SMART C+ category
  {
    name: "Smart C+ Dalandan 24/350ml",
    price: 580,
    stock: 100,
    category: "SMART C+",
    image: "",
  },
  {
    name: "Smart C+ Lemon Squeeze 24/350ml",
    price: 580,
    stock: 100,
    category: "SMART C+",
    image: "",
  },
  {
    name: "Smart C+ Orange Crush 24/350ml",
    price: 580,
    stock: 100,
    category: "SMART C+",
    image: "",
  },
  {
    name: "Smart C+ Pomelo Grapefruit 24/350ml",
    price: 580,
    stock: 100,
    category: "SMART C+",
    image: "",
  },
  {
    name: "Smart C+ Calamansi Splash 24/350ml",
    price: 580,
    stock: 100,
    category: "SMART C+",
    image: "",
  },

  // SMART C+ 500ml category
  {
    name: "Smart C+ Dalandan 24/500ml",
    price: 735,
    stock: 100,
    category: "SMART C+ 500ml",
    image: "",
  },
  {
    name: "Smart C+ Lemon Squeeze 24/500ml",
    price: 735,
    stock: 100,
    category: "SMART C+ 500ml",
    image: "",
  },
  {
    name: "Smart C+ Orange Crush 24/500ml",
    price: 735,
    stock: 100,
    category: "SMART C+ 500ml",
    image: "",
  },
  {
    name: "Smart C+ Pomelo Grapefruit 24/500ml",
    price: 735,
    stock: 100,
    category: "SMART C+ 500ml",
    image: "",
  },
  {
    name: "Smart C+ Calamansi Splash 24/500ml",
    price: 735,
    stock: 100,
    category: "SMART C+ 500ml",
    image: "",
  },
  {
    name: "Smart C+ Cranberry Dew 24/500ml",
    price: 735,
    stock: 100,
    category: "SMART C+ 500ml",
    image: "",
  },
  {
    name: "Smart C+ Honey Calamansi 24/500ml",
    price: 735,
    stock: 100,
    category: "SMART C+ 500ml",
    image: "",
  },

  // SMART C+ Liter category
  {
    name: "Smart C+ Lemon Squeeze 12/1 Liter",
    price: 610,
    stock: 100,
    category: "SMART C+ Liter",
    image: "",
  },
  {
    name: "Smart C+ Orange Crush 12/1 Liter",
    price: 610,
    stock: 100,
    category: "SMART C+ Liter",
    image: "",
  },
  {
    name: "Smart C+ Pomelo Grapefruit 12/1 Liter",
    price: 610,
    stock: 100,
    category: "SMART C+ Liter",
    image: "",
  },

  // ROYAL DAICHI category
  {
    name: "Pritong Manok",
    price: 305,
    stock: 100,
    category: "ROYAL DAICHI",
    image: "",
  },
  {
    name: "Pritong Manok [by pcs]",
    price: 6.1,
    stock: 100,
    category: "ROYAL DAICHI",
    image: "",
  },
  {
    name: "Kropeck",
    price: 305,
    stock: 100,
    category: "ROYAL DAICHI",
    image: "",
  },
  {
    name: "Kropeck [by pcs]",
    price: 6.1,
    stock: 100,
    category: "ROYAL DAICHI",
    image: "",
  },

  // DKFPI category
  {
    name: "Alibaba 15x20",
    price: 285,
    stock: 100,
    category: "DKFPI",
    image: "",
  },
  {
    name: "Alibaba [by pcs]",
    price: 19,
    stock: 100,
    category: "DKFPI",
    image: "",
  },
  {
    name: "Cheezeball 15x20",
    price: 285,
    stock: 100,
    category: "DKFPI",
    image: "",
  },
  {
    name: "Cheezeball [by pcs]",
    price: 19,
    stock: 100,
    category: "DKFPI",
    image: "",
  },
  {
    name: "Gulay 2 in 1 15x20",
    price: 285,
    stock: 100,
    category: "DKFPI",
    image: "",
  },
  {
    name: "Gulay 2 in 1 [by pcs]",
    price: 19,
    stock: 100,
    category: "DKFPI",
    image: "",
  },
  {
    name: "Lumpia 2 in1 15x20",
    price: 285,
    stock: 100,
    category: "DKFPI",
    image: "",
  },
  {
    name: "Lumpia 2 in1 [by pcs]",
    price: 19,
    stock: 100,
    category: "DKFPI",
    image: "",
  },
  {
    name: "Chocoroll 2 in 1 15x20",
    price: 285,
    stock: 100,
    category: "DKFPI",
    image: "",
  },
  {
    name: "Chocoroll 2 in 1 [by pcs]",
    price: 19,
    stock: 100,
    category: "DKFPI",
    image: "",
  },
  {
    name: "Strawberry 2 in 1 15x20",
    price: 285,
    stock: 100,
    category: "DKFPI",
    image: "",
  },
  {
    name: "Strawberry 2 in 1 [by pcs]",
    price: 19,
    stock: 100,
    category: "DKFPI",
    image: "",
  },
  {
    name: "Spag 2 in 1 15x20",
    price: 285,
    stock: 100,
    category: "DKFPI",
    image: "",
  },
  {
    name: "Spag 2 in 1 [by pcs]",
    price: 19,
    stock: 100,
    category: "DKFPI",
    image: "",
  },
  { name: "Fish Fillet", price: 305, stock: 100, category: "DKFPI", image: "" },
  {
    name: "Fish Fillet [by pcs]",
    price: 6.1,
    stock: 100,
    category: "DKFPI",
    image: "",
  },

  // LOADED 32x100 category
  {
    name: "Loaded Choco",
    price: 890,
    stock: 100,
    category: "LOADED 32x100",
    image: "",
  },
  {
    name: "Loaded Choco [by pcs]",
    price: 8.9,
    stock: 100,
    category: "LOADED 32x100",
    image: "",
  },
  {
    name: "Loaded Cheese",
    price: 890,
    stock: 100,
    category: "LOADED 32x100",
    image: "",
  },
  {
    name: "Loaded Cheese [by pcs]",
    price: 8.9,
    stock: 100,
    category: "LOADED 32x100",
    image: "",
  },
  {
    name: "Loaded White",
    price: 890,
    stock: 100,
    category: "LOADED 32x100",
    image: "",
  },
  {
    name: "Loaded White [by pcs]",
    price: 8.9,
    stock: 100,
    category: "LOADED 32x100",
    image: "",
  },

  // NUTRI 25x100 category
  {
    name: "Peewe BBQ",
    price: 810,
    stock: 100,
    category: "NUTRI 25x100",
    image: "",
  },
  {
    name: "Peewe BBQ [by pcs]",
    price: 8.1,
    stock: 100,
    category: "NUTRI 25x100",
    image: "",
  },
  {
    name: "Peewe Pizza",
    price: 810,
    stock: 100,
    category: "NUTRI 25x100",
    image: "",
  },
  {
    name: "Peewe Pizza [by pcs]",
    price: 8.1,
    stock: 100,
    category: "NUTRI 25x100",
    image: "",
  },
  {
    name: "Peewe Spicy Chili",
    price: 810,
    stock: 100,
    category: "NUTRI 25x100",
    image: "",
  },
  {
    name: "Peewe Spicy Chili [by pcs]",
    price: 8.1,
    stock: 100,
    category: "NUTRI 25x100",
    image: "",
  },
  {
    name: "Cheez It Cheese",
    price: 810,
    stock: 100,
    category: "NUTRI 25x100",
    image: "",
  },
  {
    name: "Cheez It Cheese [by pcs]",
    price: 8.1,
    stock: 100,
    category: "NUTRI 25x100",
    image: "",
  },
  {
    name: "Cheez It Cheese & Ham",
    price: 810,
    stock: 100,
    category: "NUTRI 25x100",
    image: "",
  },
  {
    name: "Cheez It Cheese & Ham [by pcs]",
    price: 8.1,
    stock: 100,
    category: "NUTRI 25x100",
    image: "",
  },
  {
    name: "Moby Choco",
    price: 810,
    stock: 100,
    category: "NUTRI 25x100",
    image: "",
  },
  {
    name: "Moby Choco [by pcs]",
    price: 8.1,
    stock: 100,
    category: "NUTRI 25x100",
    image: "",
  },
  {
    name: "Moby Caramel",
    price: 810,
    stock: 100,
    category: "NUTRI 25x100",
    image: "",
  },
  {
    name: "Moby Caramel [by pcs]",
    price: 8.1,
    stock: 100,
    category: "NUTRI 25x100",
    image: "",
  },
  {
    name: "Richee Milk",
    price: 810,
    stock: 100,
    category: "NUTRI 25x100",
    image: "",
  },
  {
    name: "Richee Milk [by pcs]",
    price: 8.1,
    stock: 100,
    category: "NUTRI 25x100",
    image: "",
  },
  {
    name: "N-Star Chicken",
    price: 810,
    stock: 100,
    category: "NUTRI 25x100",
    image: "",
  },
  {
    name: "N-Star Chicken [by pcs]",
    price: 8.1,
    stock: 100,
    category: "NUTRI 25x100",
    image: "",
  },
  {
    name: "Choco Chum Choco",
    price: 880,
    stock: 100,
    category: "NUTRI 25x100",
    image: "",
  },
  {
    name: "Choco Chum Choco [by pcs]",
    price: 8.8,
    stock: 100,
    category: "NUTRI 25x100",
    image: "",
  },
  {
    name: "Choco Chum White",
    price: 880,
    stock: 100,
    category: "NUTRI 25x100",
    image: "",
  },
  {
    name: "Choco Chum White [by pcs]",
    price: 8.8,
    stock: 100,
    category: "NUTRI 25x100",
    image: "",
  },

  // NUTRI 60x50 category
  {
    name: "Peewe BBQ",
    price: 890,
    stock: 100,
    category: "NUTRI 60x50",
    image: "",
  },
  {
    name: "Peewe BBQ [by pcs]",
    price: 17.8,
    stock: 100,
    category: "NUTRI 60x50",
    image: "",
  },
  {
    name: "Peewe Pizza",
    price: 890,
    stock: 100,
    category: "NUTRI 60x50",
    image: "",
  },
  {
    name: "Peewe Pizza [by pcs]",
    price: 17.8,
    stock: 100,
    category: "NUTRI 60x50",
    image: "",
  },
  {
    name: "Peewe Spicy Chili",
    price: 890,
    stock: 100,
    category: "NUTRI 60x50",
    image: "",
  },
  {
    name: "Peewe Spicy Chili [by pcs]",
    price: 17.8,
    stock: 100,
    category: "NUTRI 60x50",
    image: "",
  },
  {
    name: "Cheez It Cheese",
    price: 890,
    stock: 100,
    category: "NUTRI 60x50",
    image: "",
  },
  {
    name: "Cheez It Cheese [by pcs]",
    price: 17.8,
    stock: 100,
    category: "NUTRI 60x50",
    image: "",
  },
  {
    name: "Cheez It Cheese & Ham",
    price: 890,
    stock: 100,
    category: "NUTRI 60x50",
    image: "",
  },
  {
    name: "Cheez It Cheese & Ham [by pcs]",
    price: 17.8,
    stock: 100,
    category: "NUTRI 60x50",
    image: "",
  },
  {
    name: "Moby Choco",
    price: 890,
    stock: 100,
    category: "NUTRI 60x50",
    image: "",
  },
  {
    name: "Moby Choco [by pcs]",
    price: 17.8,
    stock: 100,
    category: "NUTRI 60x50",
    image: "",
  },
  {
    name: "Moby Caramel",
    price: 890,
    stock: 100,
    category: "NUTRI 60x50",
    image: "",
  },
  {
    name: "Moby Caramel [by pcs]",
    price: 17.8,
    stock: 100,
    category: "NUTRI 60x50",
    image: "",
  },
  {
    name: "Richee Milk",
    price: 890,
    stock: 100,
    category: "NUTRI 60x50",
    image: "",
  },
  {
    name: "Richee Milk [by pcs]",
    price: 17.8,
    stock: 100,
    category: "NUTRI 60x50",
    image: "",
  },
  {
    name: "Choco Chum Choco",
    price: 950,
    stock: 100,
    category: "NUTRI 60x50",
    image: "",
  },
  {
    name: "Choco Chum Choco [by pcs]",
    price: 9.5,
    stock: 100,
    category: "NUTRI 60x50",
    image: "",
  },
  {
    name: "Choco Chum White",
    price: 950,
    stock: 100,
    category: "NUTRI 60x50",
    image: "",
  },
  {
    name: "Choco Chum White [by pcs]",
    price: 9.5,
    stock: 100,
    category: "NUTRI 60x50",
    image: "",
  },

  // NUTRI 90x25 category
  {
    name: "Peewe BBQ",
    price: 740,
    stock: 100,
    category: "NUTRI 90x25",
    image: "",
  },
  {
    name: "Peewe BBQ [by pcs]",
    price: 29.6,
    stock: 100,
    category: "NUTRI 90x25",
    image: "",
  },
  {
    name: "Peewe Pizza",
    price: 740,
    stock: 100,
    category: "NUTRI 90x25",
    image: "",
  },
  {
    name: "Peewe Pizza [by pcs]",
    price: 29.6,
    stock: 100,
    category: "NUTRI 90x25",
    image: "",
  },
  {
    name: "Peewe Spicy Chili",
    price: 740,
    stock: 100,
    category: "NUTRI 90x25",
    image: "",
  },
  {
    name: "Peewe Spicy Chili [by pcs]",
    price: 29.6,
    stock: 100,
    category: "NUTRI 90x25",
    image: "",
  },
  {
    name: "Cheez It Cheese",
    price: 740,
    stock: 100,
    category: "NUTRI 90x25",
    image: "",
  },
  {
    name: "Cheez It Cheese [by pcs]",
    price: 29.6,
    stock: 100,
    category: "NUTRI 90x25",
    image: "",
  },
  {
    name: "Cheez It Cheese & Ham",
    price: 740,
    stock: 100,
    category: "NUTRI 90x25",
    image: "",
  },
  {
    name: "Cheez It Cheese & Ham [by pcs]",
    price: 29.6,
    stock: 100,
    category: "NUTRI 90x25",
    image: "",
  },
  {
    name: "Moby Choco",
    price: 740,
    stock: 100,
    category: "NUTRI 90x25",
    image: "",
  },
  {
    name: "Moby Choco [by pcs]",
    price: 29.6,
    stock: 100,
    category: "NUTRI 90x25",
    image: "",
  },
  {
    name: "Moby Caramel",
    price: 740,
    stock: 100,
    category: "NUTRI 90x25",
    image: "",
  },
  {
    name: "Moby Caramel [by pcs]",
    price: 29.6,
    stock: 100,
    category: "NUTRI 90x25",
    image: "",
  },
  {
    name: "Richee Milk",
    price: 740,
    stock: 100,
    category: "NUTRI 90x25",
    image: "",
  },
  {
    name: "Richee Milk [by pcs]",
    price: 29.6,
    stock: 100,
    category: "NUTRI 90x25",
    image: "",
  },

  // LONBISCO category
  {
    name: "Hebi 12x20's",
    price: 246,
    stock: 100,
    category: "LONBISCO",
    image: "",
  },
  {
    name: "Hebi 12x20's [by pcs]",
    price: 20.5,
    stock: 100,
    category: "LONBISCO",
    image: "",
  },
  {
    name: "Domino 42x10's",
    price: 1953,
    stock: 100,
    category: "LONBISCO",
    image: "",
  },
  {
    name: "Domino 42x10's [by pcs]",
    price: 46.5,
    stock: 100,
    category: "LONBISCO",
    image: "",
  },

  // LESLIE'S category
  {
    name: "Cheezy Corn Crunch Puffs",
    price: 760,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy Corn Crunch Puffs [by pcs]",
    price: 7.6,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy-O Cheese 75g",
    price: 585,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy-O Cheese [by pcs]",
    price: 7.65,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy Red Hot 40/100g",
    price: 760,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy Red Hot [by pcs]",
    price: 7.6,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy Original 40/100g",
    price: 760,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy Original [by pcs]",
    price: 7.6,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy Ghost Pepper 40/100g",
    price: 760,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy Ghost Pepper [by pcs]",
    price: 7.6,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy Red Hot 85g",
    price: 1110,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy Red Hot [by pcs]",
    price: 27.75,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy Original 85g",
    price: 1110,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy Original [by pcs]",
    price: 27.75,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy Ghost Pepper 85g",
    price: 1110,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy Ghost Pepper [by pcs]",
    price: 27.75,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover BBQ 105/24g",
    price: 803,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover BBQ [by pcs]",
    price: 7.65,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover Cheese 105/24g",
    price: 803,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover Cheese [by pcs]",
    price: 7.65,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover Chilli & Cheese 105/24g",
    price: 803,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover Chilli & Cheese [by pcs]",
    price: 7.65,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover BBQ 30/85g",
    price: 1210,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover BBQ [by pcs]",
    price: 33.62,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover Cheese 30/85g",
    price: 1210,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover Cheese [by pcs]",
    price: 33.62,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover Chilli & Cheese 30/85g",
    price: 1210,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover Chilli & Cheese [by pcs]",
    price: 33.62,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover Bits BBQ",
    price: 785,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover Bits BBQ [by pcs]",
    price: 7.85,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover Bits Chicken",
    price: 785,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover Bits Chicken [by pcs]",
    price: 7.85,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Nacho BBQ",
    price: 760,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Nacho BBQ [by pcs]",
    price: 7.6,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Nacho Cheese",
    price: 760,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Nacho Cheese [by pcs]",
    price: 7.6,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },

  // PURESNACK category
  {
    name: "Inihaw na Bangus 50gx25",
    price: 190,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Inihaw na Bangus [by pcs]",
    price: 7.6,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Kapitan Tuna 50gx25",
    price: 190,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Kapitan Tuna [by pcs]",
    price: 7.6,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Crab Big 50gx25",
    price: 190,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Crab Big [by pcs]",
    price: 7.6,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Sarap Asim Big",
    price: 190,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Sarap Asim Big [by pcs]",
    price: 7.6,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Potitos Cheese Big",
    price: 190,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Potitos Cheese Big [by pcs]",
    price: 7.6,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Potitos Onion Big",
    price: 190,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Potitos Onion Big [by pcs]",
    price: 7.6,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Dynamite 50gx25",
    price: 190,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Dynamite [by pcs]",
    price: 7.6,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Pritong Bangus",
    price: 190,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Pritong Bangus [by pcs]",
    price: 7.6,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Spicy Paksiw",
    price: 190,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Spicy Paksiw [by pcs]",
    price: 7.6,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Moonchips",
    price: 190,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Moonchips [by pcs]",
    price: 7.6,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },

  // Continue with other categories...
  // FAMILY, BEERMATCH, SUNDAYS, MARSHMALLOW, BREADPAN, PINATSU, FROOZE, SMART C+, etc.
];

async function seedProducts() {
  let successCount = 0;
  let errorCount = 0;

  // Add delay function to avoid rate limiting
  const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

  for (let i = 0; i < products.length; i++) {
    try {
      await addDoc(collection(db, "products"), products[i]);
      console.log(`Added ${products[i].name}`);
      successCount++;

      // Add a small delay every 50 products to avoid rate limiting
      if (i % 50 === 0 && i > 0) {
        console.log("Taking a brief pause to avoid rate limiting...");
        await delay(1000); // 1 second delay
      }
    } catch (error) {
      console.error(`Error adding ${products[i].name}:`, error);
      errorCount++;

      // Longer delay on error
      await delay(2000);
    }
  }

  console.log(
    `Seeding complete! Success: ${successCount}, Errors: ${errorCount}`
  );
}

seedProducts().catch(console.error);
