import { initializeApp } from "firebase/app";
import { getFirestore, collection, addDoc } from "firebase/firestore";
import { firebaseConfig } from "./src/Firebase/firebase.js";

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const products = [
  // NUTRI products
  {
    name: "Peewe BBQ [by pcs]",
    price: 29.6,
    stock: 100,
    category: "NUTRI",
    image: "",
  },
  {
    name: "Peewe Pizza",
    price: 740,
    stock: 100,
    category: "NUTRI",
    image: "",
  },
  {
    name: "Peewe Pizza [by pcs]",
    price: 29.6,
    stock: 100,
    category: "NUTRI",
    image: "",
  },
  {
    name: "Peewe Spicy Chili",
    price: 740,
    stock: 100,
    category: "NUTRI",
    image: "",
  },
  {
    name: "Peewe Spicy Chili [by pcs]",
    price: 29.6,
    stock: 100,
    category: "NUTRI",
    image: "",
  },
  {
    name: "Cheez It Cheese",
    price: 740,
    stock: 100,
    category: "NUTRI",
    image: "",
  },
  {
    name: "Cheez It Cheese [by pcs]",
    price: 29.6,
    stock: 100,
    category: "NUTRI",
    image: "",
  },
  {
    name: "Cheez It Cheese & Ham",
    price: 740,
    stock: 100,
    category: "NUTRI",
    image: "",
  },
  {
    name: "Cheez It Cheese & Ham [by pcs]",
    price: 29.6,
    stock: 100,
    category: "NUTRI",
    image: "",
  },
  {
    name: "Moby Choco",
    price: 740,
    stock: 100,
    category: "NUTRI",
    image: "",
  },
  {
    name: "Moby Choco [by pcs]",
    price: 29.6,
    stock: 100,
    category: "NUTRI",
    image: "",
  },
  {
    name: "Moby Caramel",
    price: 740,
    stock: 100,
    category: "NUTRI",
    image: "",
  },
  {
    name: "Moby Caramel [by pcs]",
    price: 29.6,
    stock: 100,
    category: "NUTRI",
    image: "",
  },
  {
    name: "Richee Milk",
    price: 740,
    stock: 100,
    category: "NUTRI",
    image: "",
  },
  {
    name: "Richee Milk [by pcs]",
    price: 29.6,
    stock: 100,
    category: "NUTRI",
    image: "",
  },

  // LONBISCO products
  {
    name: "Hebi 12x20's",
    price: 246,
    stock: 100,
    category: "LONBISCO",
    image: "",
  },
  {
    name: "Hebi 12x20's [by pcs]",
    price: 20.5,
    stock: 100,
    category: "LONBISCO",
    image: "",
  },
  {
    name: "Domino 42x10's",
    price: 1953,
    stock: 100,
    category: "LONBISCO",
    image: "",
  },
  {
    name: "Domino 42x10's [by pcs]",
    price: 46.5,
    stock: 100,
    category: "LONBISCO",
    image: "",
  },

  // LESLIE'S products
  {
    name: "Cheezy Corn Crunch Puffs",
    price: 760,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy Corn Crunch Puffs [by pcs]",
    price: 7.6,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy-O Cheese 75g",
    price: 585,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy-O Cheese [by pcs]",
    price: 7.65,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy Red Hot 40/100g",
    price: 760,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy Red Hot [by pcs]",
    price: 7.6,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy Original 40/100g",
    price: 760,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy Original [by pcs]",
    price: 7.6,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy Ghost Pepper 40/100g",
    price: 760,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy Ghost Pepper [by pcs]",
    price: 7.6,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy Red Hot 85g",
    price: 1110,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy Red Hot 85g [by pcs]",
    price: 27.75,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy Original 85g",
    price: 1110,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy Original 85g [by pcs]",
    price: 27.75,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy Ghost Pepper 85g",
    price: 1110,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Cheezy Ghost Pepper 85g [by pcs]",
    price: 27.75,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover BBQ 105/24g",
    price: 803,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover BBQ [by pcs]",
    price: 7.65,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover Cheese 105/24g",
    price: 803,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover Cheese [by pcs]",
    price: 7.65,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover Chilli & Cheese 105/24g",
    price: 803,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover Chilli & Cheese [by pcs]",
    price: 7.65,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover BBQ 30/85g",
    price: 1210,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover BBQ 30/85g [by pcs]",
    price: 33.62,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover Cheese 30/85g",
    price: 1210,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover Cheese 30/85g [by pcs]",
    price: 33.62,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover Chilli & Cheese 30/85g",
    price: 1210,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover Chilli & Cheese 30/85g [by pcs]",
    price: 33.62,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover Bits BBQ",
    price: 785,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover Bits BBQ [by pcs]",
    price: 7.85,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover Bits Chicken",
    price: 785,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Clover Bits Chicken [by pcs]",
    price: 7.85,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Nacho BBQ",
    price: 760,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Nacho BBQ [by pcs]",
    price: 7.6,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Nacho Cheese",
    price: 760,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },
  {
    name: "Nacho Cheese [by pcs]",
    price: 7.6,
    stock: 100,
    category: "LESLIE'S",
    image: "",
  },

  // PURESNACK products
  {
    name: "Inihaw na Bangus 50gx25",
    price: 190,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Inihaw na Bangus [by pcs]",
    price: 7.6,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Kapitan Tuna 50gx25",
    price: 190,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Kapitan Tuna [by pcs]",
    price: 7.6,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Crab Big 50gx25",
    price: 190,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Crab Big [by pcs]",
    price: 7.6,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Sarap Asim Big",
    price: 190,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Sarap Asim Big [by pcs]",
    price: 7.6,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Potitos Cheese Big",
    price: 190,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Potitos Cheese Big [by pcs]",
    price: 7.6,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Potitos Onion Big",
    price: 190,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Potitos Onion Big [by pcs]",
    price: 7.6,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Dynamite 50gx25",
    price: 190,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Dynamite [by pcs]",
    price: 7.6,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Pritong Bangus",
    price: 190,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Pritong Bangus [by pcs]",
    price: 7.6,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Spicy Paksiw",
    price: 190,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Spicy Paksiw [by pcs]",
    price: 7.6,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Moonchips",
    price: 190,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
  {
    name: "Moonchips [by pcs]",
    price: 7.6,
    stock: 100,
    category: "PURESNACK",
    image: "",
  },
];

async function seedProducts() {
  for (const product of products) {
    await addDoc(collection(db, "products"), product);
    console.log(`Added ${product.name}`);
  }
  console.log("Seeding complete!");
}

seedProducts();
