// seed/seed.js
import { initializeApp } from "firebase/app";
import { getFirestore, collection, addDoc } from "firebase/firestore";
import { firebaseConfig } from "./src/Firebase/firebase.js";

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const products = [
  {
    name: "Chippy BBQ",
    price: 15,
    stock: 100,
    category: "Chips",
    image: "https://firebasestorage.googleapis.com/.../chippy.png",
  },
  {
    name: "Piattos Cheese",
    price: 20,
    stock: 80,
    category: "Chips",
    image: "https://firebasestorage.googleapis.com/.../piattos.png",
  },
  {
    name: "Nova Multigrain",
    price: 18,
    stock: 50,
    category: "Chips",
    image: "https://firebasestorage.googleapis.com/.../nova.png",
  },
  {
    name: "Ding Dong Mixed Nuts",
    price: 12,
    stock: 70,
    category: "Nuts",
    image: "https://firebasestorage.googleapis.com/.../dingdong.png",
  },
  {
    name: "Fish Cracker 100/24g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../fish_cracker.png",
  },
  {
    name: "Fish Cracker [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../fish_cracker.png",
  },
  {
    name: "Crackling Salt & Vinegar 100/24g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../crackling.png",
  },
  {
    name: "Crackling Salt & Vinegar [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../crackling.png",
  },
  {
    name: "Crispy Patata 100/24g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../crispy_patata.png",
  },
  {
    name: "Crispy Patata [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../crispy_patata.png",
  },
  {
    name: "Crispy Patata Cheese 100/24g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image:
      "https://firebasestorage.googleapis.com/.../crispy_patata_cheese.png",
  },
  {
    name: "Crispy Patata Cheese [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image:
      "https://firebasestorage.googleapis.com/.../crispy_patata_cheese.png",
  },
  {
    name: "Oishi Fisda Fish Kropeck 100/22g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../fisda.png",
  },
  {
    name: "Oishi Fisda Fish Kropeck [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../fisda.png",
  },
  {
    name: "Cheez on Chips 100/22g",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../cheez_on_chips.png",
  },
  {
    name: "Cheez on Chips [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../cheez_on_chips.png",
  },
  {
    name: "Rinbee Cheese Stick 100/24g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../rinbee.png",
  },
  {
    name: "Rinbee Cheese Stick [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../rinbee.png",
  },
  {
    name: "Onion Ring 100/16g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../onion_ring.png",
  },
  {
    name: "Onion Ring [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../onion_ring.png",
  },
  {
    name: "Boogyman Crunch 100/24g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../boogyman.png",
  },
  {
    name: "Boogyman Crunch [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../boogyman.png",
  },
  {
    name: "Kirei Yummy Flakes 100/24g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../kirei.png",
  },
  {
    name: "Kirei Yummy Flakes [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../kirei.png",
  },
  {
    name: "Kirei Yummy Flakes Spicy Shrimp 100/20g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../kirei_spicy.png",
  },
  {
    name: "Kirei Yummy Flakes Spicy Shrimp [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../kirei_spicy.png",
  },
  {
    name: "Spicy Seafood Curls 100/24g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../seafood_curls.png",
  },
  {
    name: "Spicy Seafood Curls [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../seafood_curls.png",
  },
  {
    name: "Oishi Chokulot Choco Curls 100/22g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../chokulot.png",
  },
  {
    name: "Choco Lo 100/32g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../choco_lo.png",
  },
  {
    name: "Choco Lo [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../choco_lo.png",
  },
  {
    name: "Oishi OHEYA Multi Grain Cheese 100/28g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../oheya.png",
  },
  {
    name: "Oishi OHEYA Multi Grain Cheese [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../oheya.png",
  },
  {
    name: "Potato Fries Cheese 100/21g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../potato_fries_cheese.png",
  },
  {
    name: "Potato Fries Cheese [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../potato_fries_cheese.png",
  },
  {
    name: "Potato Fries Plain Salted 100/21g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../potato_fries_plain.png",
  },
  {
    name: "Potato Fries Plain Salted [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../potato_fries_plain.png",
  },
  {
    name: "Potato Fries Barbecue Flavor 100/21g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../potato_fries_bbq.png",
  },
  {
    name: "Potato Fries Barbecue Flavor [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../potato_fries_bbq.png",
  },
  {
    name: "Potato Fries Tomato Ketchup 100/21g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image:
      "https://firebasestorage.googleapis.com/.../potato_fries_ketchup.png",
  },
  {
    name: "Potato Fries Tomato Ketchup [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image:
      "https://firebasestorage.googleapis.com/.../potato_fries_ketchup.png",
  },
  {
    name: "Oishi Prawn Cracker Spicy 100g/24g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../prawn_spicy.png",
  },
  {
    name: "Oishi Prawn Cracker Spicy [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../prawn_spicy.png",
  },
  {
    name: "Oishi Prawn Cracker Sweet&Extra Hot 24g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../prawn_hot.png",
  },
  {
    name: "Oishi Prawn Cracker Sweet&Extra Hot [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../prawn_hot.png",
  },
  {
    name: "Oishi Prawn Cracker Plain 100/24g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../prawn_plain.png",
  },
  {
    name: "Oishi Prawn Cracker Plain [by pcs]",
    price: 0.68,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../prawn_plain.png",
  },
  {
    name: "Marty's Cracklin' Spicy Flavor 100/26g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../marty_spicy.png",
  },
  {
    name: "Marty's Cracklin' Spicy Flavor [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../marty_spicy.png",
  },
  {
    name: "Martyrs Plain Salted 100/26g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../marty_plain.png",
  },
  {
    name: "Martyrs Plain Salted [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../marty_plain.png",
  },
  {
    name: "Marty's Salted and Vinegar 100/26g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../marty_vinegar.png",
  },
  {
    name: "Marty's Salted and Vinegar [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../marty_vinegar.png",
  },
  {
    name: "Marty's Chicken Inasal 100/26g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../marty_inasal.png",
  },
  {
    name: "Marty's Chicken Inasal [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../marty_inasal.png",
  },
  {
    name: "Choco Pillows 100/24g",
    price: 670,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../choco_pillows.png",
  },
  {
    name: "Choco Pillows [by pcs]",
    price: 6.7,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../choco_pillows.png",
  },
  {
    name: "Ube Pillows 100/24g",
    price: 670,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../ube_pillows.png",
  },
  {
    name: "Ube Pillows [by pcs]",
    price: 6.7,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../ube_pillows.png",
  },
  {
    name: "Choco Pillows 100/38g",
    price: 890,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../choco_pillows_large.png",
  },
  {
    name: "Choco Pillows [by pcs]",
    price: 8.9,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../choco_pillows_large.png",
  },
  {
    name: "Ube Pillows 100/38g",
    price: 690,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../ube_pillows_large.png",
  },
  {
    name: "Ube Pillows [by pcs]",
    price: 6.9,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../ube_pillows_large.png",
  },
  {
    name: "Oishi Chocolate Popcorn 50/60g",
    price: 850,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../choco_popcorn.png",
  },
  {
    name: "Oishi Chocolate Popcorn [by pcs]",
    price: 17,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../choco_popcorn.png",
  },
  {
    name: "Oishi Caramel Popcorn 50/60g",
    price: 850,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../caramel_popcorn.png",
  },
  {
    name: "Oishi Caramel Popcorn [by pcs]",
    price: 17,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../caramel_popcorn.png",
  },
  {
    name: "Oishi Tater Thins Potato Snack 100g/18g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../tater_thins.png",
  },
  {
    name: "Oishi Tater Thins Potato Snack [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../tater_thins.png",
  },
  {
    name: "Pods Vegetarian Pea Snack 100/28g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../pods.png",
  },
  {
    name: "Pods Vegetarian Pea Snack [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../pods.png",
  },
  {
    name: "Oishi Shripon Shrimp Kropeck 100/20g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../shripon.png",
  },
  {
    name: "Oishi Shripon Shrimp Kropeck [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../shripon.png",
  },
  {
    name: "Corn Ole' 100/22g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../corn_ole.png",
  },
  {
    name: "Corn Ole' [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../corn_ole.png",
  },
  {
    name: "Cheese Clubs 100/23g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../cheese_clubs.png",
  },
  {
    name: "Cheese Clubs [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../cheese_clubs.png",
  },
  {
    name: "Oishi Crackle Nets BBQ 100/24g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../crackle_nets.png",
  },
  {
    name: "Oishi Crackle Nets BBQ [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../crackle_nets.png",
  },
  {
    name: "Oishi KARLS Corn Cheese 100/35g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../karls.png",
  },
  {
    name: "Oishi KARLS Corn Cheese [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../karls.png",
  },
  {
    name: "Oishi Miggos Sweetcorn 100/28g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../miggos_sweetcorn.png",
  },
  {
    name: "Oishi Miggos Sweetcorn [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../miggos_sweetcorn.png",
  },
  {
    name: "Oishi Miggos Nacho Cheese 100/28g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../miggos_nacho.png",
  },
  {
    name: "Oishi Miggos Nacho Cheese [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../miggos_nacho.png",
  },
  {
    name: "4X Corn Snack Cheddar Cheese 100/24g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../4x_cheddar.png",
  },
  {
    name: "4X Corn Snack Cheddar Cheese [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../4x_cheddar.png",
  },
  {
    name: "4X Corn Snack BBQ 100/24g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../4x_bbq.png",
  },
  {
    name: "4X Corn Snack BBQ [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../4x_bbq.png",
  },
  {
    name: "4X Corn Snack Sweet Corn 100/24g",
    price: 680,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../4x_sweetcorn.png",
  },
  {
    name: "4X Corn Snack Sweet Corn [by pcs]",
    price: 6.8,
    stock: 100,
    category: "LARGE",
    image: "https://firebasestorage.googleapis.com/.../4x_sweetcorn.png",
  },

  {
    name: "Fish Cracker 30/90g",
    price: 750,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../fish_cracker_ua.png",
  },
  {
    name: "Fish Cracker [by pcs]",
    price: 25,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../fish_cracker_ua.png",
  },
  {
    name: "Crackling Salt & Vinegar 30/90g",
    price: 750,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../crackling_ua.png",
  },
  {
    name: "Crackling Salt & Vinegar [by pcs]",
    price: 25,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../crackling_ua.png",
  },
  {
    name: "Crispy Patata 30/85g",
    price: 750,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../crispy_patata_ua.png",
  },
  {
    name: "Crispy Patata [by pcs]",
    price: 25,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../crispy_patata_ua.png",
  },
  {
    name: "Crispy Patata Cheese 30/85g",
    price: 750,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image:
      "https://firebasestorage.googleapis.com/.../crispy_patata_cheese_ua.png",
  },
  {
    name: "Crispy Patata Cheese [by pcs]",
    price: 25,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image:
      "https://firebasestorage.googleapis.com/.../crispy_patata_cheese_ua.png",
  },
  {
    name: "Fisda Fish Kropek 15/80g",
    price: 350,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../fisda_ua.png",
  },
  {
    name: "Fisda Fish Kropek [by pcs]",
    price: 23.34,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../fisda_ua.png",
  },
  {
    name: "Rinbee Cheese Stick 30/85g",
    price: 750,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../rinbee_ua.png",
  },
  {
    name: "Rinbee Cheese Stick [by pcs]",
    price: 25,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../rinbee_ua.png",
  },
  {
    name: "Kirei Yummy Flakes 30/60g",
    price: 750,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../kirei_ua.png",
  },
  {
    name: "Kirei Yummy Flakes [by pcs]",
    price: 25,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../kirei_ua.png",
  },
  {
    name: "Spicy Sea Food Curls 30/90g",
    price: 750,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../seafood_curls_ua.png",
  },
  {
    name: "Spicy Sea Food Curls [by pcs]",
    price: 25,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../seafood_curls_ua.png",
  },
  {
    name: "Potato Fries Cheese 30/90g",
    price: 750,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image:
      "https://firebasestorage.googleapis.com/.../potato_fries_cheese_ua.png",
  },
  {
    name: "Potato Fries Cheese [by pcs]",
    price: 25,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image:
      "https://firebasestorage.googleapis.com/.../potato_fries_cheese_ua.png",
  },
  {
    name: "Potato Fries Plain Salted 30/90g",
    price: 750,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image:
      "https://firebasestorage.googleapis.com/.../potato_fries_plain_ua.png",
  },
  {
    name: "Potato Fries Plain Salted [by pcs]",
    price: 25,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image:
      "https://firebasestorage.googleapis.com/.../potato_fries_plain_ua.png",
  },
  {
    name: "Oishi Prawn Crackers Spicy 30/100g",
    price: 750,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../prawn_spicy_ua.png",
  },
  {
    name: "Oishi Prawn Crackers Spicy [by pcs]",
    price: 25,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../prawn_spicy_ua.png",
  },
  {
    name: "Oishi Prawn Crackers Extra Hot 30/100g",
    price: 750,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../prawn_hot_ua.png",
  },
  {
    name: "Oishi Prawn Crackers Extra Hot [by pcs]",
    price: 25,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../prawn_hot_ua.png",
  },
  {
    name: "Oishi Prawn Crackers Plain 30/100g",
    price: 750,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../prawn_plain_ua.png",
  },
  {
    name: "Oishi Prawn Crackers Plain [by pcs]",
    price: 25,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../prawn_plain_ua.png",
  },
  {
    name: "Marty's Cracklin' Spicy Flavor 30/90g",
    price: 670,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../marty_spicy_ua.png",
  },
  {
    name: "Marty's Cracklin' Spicy Flavor [by pcs]",
    price: 22.34,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../marty_spicy_ua.png",
  },
  {
    name: "Martyrs Plain 30/90g",
    price: 670,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../marty_plain_ua.png",
  },
  {
    name: "Martyrs Plain [by pcs]",
    price: 22.34,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../marty_plain_ua.png",
  },
  {
    name: "Marty's Salt and Vinegar 30/90g",
    price: 670,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../marty_vinegar_ua.png",
  },
  {
    name: "Marty's Salt and Vinegar [by pcs]",
    price: 22.34,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../marty_vinegar_ua.png",
  },
  {
    name: "Marty's Chicken Inasal 30/90g",
    price: 670,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../marty_inasal_ua.png",
  },
  {
    name: "Marty's Chicken Inasal [by pcs]",
    price: 22.34,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../marty_inasal_ua.png",
  },
  {
    name: "Marty's Cracklin' Baconette 30/90g",
    price: 800,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../marty_baconette.png",
  },
  {
    name: "Marty's Cracklin' Baconette [by pcs]",
    price: 27,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../marty_baconette.png",
  },
  {
    name: "Oishi Tater Thins Potato Snack 30/75g",
    price: 750,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../tater_thins_ua.png",
  },
  {
    name: "Oishi Tater Thins Potato Snack [by pcs]",
    price: 25,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../tater_thins_ua.png",
  },
  {
    name: "O-Pusit Sweet Spicy 30/80g",
    price: 750,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../opusit.png",
  },
  {
    name: "O-Pusit Sweet Spicy [by pcs]",
    price: 25,
    stock: 100,
    category: "EXTRA SIZE (UA)",
    image: "https://firebasestorage.googleapis.com/.../opusit.png",
  },
];

async function seedProducts() {
  for (const product of products) {
    await addDoc(collection(db, "products"), product);
    console.log(`Added ${product.name}`);
  }
  console.log("Seeding complete!");
}

seedProducts();
